export const Action = {
  BOLD: 'bold',
  ITALIC: 'italic',
  UNDERLINE: 'underline',
  STRIKE_THROUGH: 'strikeThrough',
  ALIGN_LEFT: 'justifyLeft',
  ALIGN_CENTER: 'justifyCenter',
  ALIGN_RIGHT: 'justifyRight',
  ALIGN_JUSTIFY: 'justifyFull',
  TEXT_COLOR: 'foreColor',
  BACKGROUND_COLOR: 'hiliteColor',
  INDENT: 'indent',
  OUTDENT: 'outdent',
  ORDERED_LIST: 'insertOrderedList',
  UNORDERED_LIST: 'insertUnorderedList',
  SUBSCRIPT: 'subscript',
  SUPERSCRIPT: 'superscript',
  FORMAT_BLOCK: 'formatBlock',
  INSERT_BR_ON_RETURN: 'insertBrOnReturn',
  REMOVE_FORMAT: 'removeFormat',
  STYLE_WITH_CSS: 'styleWithCSS'
};
